export class Defines { 
    public static Stocks = [{id:1,name:"Vianet"},
   {id: 2,name:"Agritek"},
   {id: 3,name:"Akamai"},
   {id: 4,name:"Baidu"},
   {id: 5,name:"Blinkx"},
   {id: 6,name:"Blucora"},
   {id: 7,name:"Boingo"},
   {id: 8,name:"Brainybrawn"},
   {id: 9,name:"Carbonite"},
   {id: 10,name:"China Finance"},
   {id: 11,name:"ChinaCache"},
   {id: 12,name:"ADR"},
   {id: 13,name:"ChitrChatr"},
   {id: 14,name:"Cnova"},
   {id: 15,name:"Cogent"},
   {id: 16,name:"Crexendo"},
   {id: 17,name:"CrowdGather"},
   {id: 18,name:"EarthLink"},
   {id: 19,name:"Eastern"},
   {id: 20,name:"ENDEXX"},
   {id: 21,name:"Envestnet"},
   {id: 22,name:"Epazz"},
   { id:23,name:"FlashZero"},
   { id:24,name:"Genesis"},
    {id:25,name:"InterNAP"},
   { id:26,name:"MeetMe"},
    {id:27,name:"Netease"},
    {id:28,name:"Qihoo"}]
    
}